services:
  ng-shared-components:
    build:
      context: ../
    image: ${IMAGE:-ng-shared-components}
    container_name: ${CONTAINER_NAME:-ng-shared-components}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 3s
